from roofing_app.job_manager import JobManager
import random
from datetime import datetime, timedelta

def seed_database(num_jobs=30):
    print("Seeding database with dummy data...")
    mgr = JobManager()

    # Check if we already have data to avoid over-seeding in dev
    if len(mgr.get_jobs()) > 5:
        print("Database already has data. Skipping seed.")
        return

    statuses = ["Lead", "Estimate Sent", "Signed", "In Progress", "Completed"]
    sources = ["Website", "Referral", "Google Ads", "Door Knocking", "Facebook"]

    for i in range(num_jobs):
        val = random.randint(5000, 35000)
        status = random.choice(statuses)
        source = random.choice(sources)

        # Random date in last 60 days
        days_ago = random.randint(0, 60)
        date = datetime.now() - timedelta(days=days_ago)

        # We manipulate the created_at by raw SQL because add_job uses now()
        # But for MVP prototype, just adding them now is fine, OR we can hack it.
        # Let's just use add_job and accept they are all "today" for sorting,
        # but for analytics based on "status" and "value", it matters less.
        # Actually, for "Performance" over time, dates matter.
        # Let's insert manually to force dates.

        import sqlite3
        conn = sqlite3.connect("roofing_jobs.db")
        c = conn.cursor()
        c.execute('''
            INSERT INTO jobs (customer_name, address, value, status, created_at, notes, lead_source)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        ''', (
            f"Customer {i+1}",
            f"{random.randint(100,999)} Oak St",
            val,
            status,
            date,
            "Generated by seed script",
            source
        ))
        conn.commit()
        conn.close()

    print(f"Successfully added {num_jobs} jobs.")

if __name__ == "__main__":
    seed_database()
